#!/bin/bash

# Created by Shichu on Nov 1, 2015
# Need environmental variables $keelingpath and $localpath to be set

interactive=y
safemode=n

#set -v

while getopts "udsk:l:h" opt; do
  case $opt in
    k)
      echo "Temporal Keeling path set to $OPTARG"
	  keelingpath=$OPTARG
	  echo "Note USE mtkeeling path!!!!"
      ;;
    l)
      echo "Temporal Local path set to $OPTARG"
	  localpath=$OPTARG
      ;;
    u)
      echo "Explicit UPLOADING mode..."
	  interactive=u
      ;;
    d)
      echo "Explicit DOWNLOADING mode..."
	  interactive=d
      ;;
    s)
		echo "Safe mode (without --delete option)..."
	  safemode=y
      ;;
    h)
		echo "(H)elp information (All options lower case):"
		echo "(U)pload, (D)ownload, (S)afemode without --delete"
		echo "Set (K)eeling path, or (L)ocal path."
		exit
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

syncdirname=$(basename $keelingpath)
uploadkeelingpath=${keelingpath%/*}
uploadlocalpath=$localpath/$syncdirname

echo "Keeling and local directories:*****************"
echo $keelingpath
echo $localpath
echo "***********************************************"

if [ "$interactive" = "y" ]; then
	echo "Enter [d] for download, or [u] for upload:"
	read operation
	if [ "$operation" != "d" -a "$operation" != "u" ]; then
		echo "Error: Input argument not recognized!"
		exit 0
	fi
else
	operation=$interactive
fi

if [ "$safemode" = "n" ]; then
	delarg="--delete"
elif [ "$safemode" = "y" ]; then
	delarg=""
else
	echo "Not sure if safemode or not, exitting..."
	exit
fi

if [ "$operation" = "d" ]; then
	rsync --dry-run $delarg --links --update -r -t -v --progress -s $keelingpath $localpath
elif [ "$operation" = "u" ]; then
	rsync --dry-run $delarg --links --update -r -t -v --progress -s $uploadlocalpath $uploadkeelingpath
fi

echo "Press [y] to confirm, otherwise quit ... ..."
read confirm
if [ "$confirm" != "y" ]; then
	echo "Quit without execution!"
	exit
fi

if [ "$operation" = "d" ]; then
	rsync $delarg --links --update -r -t -v --progress -s $keelingpath $localpath
elif [ "$operation" = "u" ]; then
	rsync $delarg --links --update -r -t -v --progress -s $uploadlocalpath $uploadkeelingpath
fi
