# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH=/home/shichu/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="robbyrussell"
ZSH_THEME="agnoster"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
# -------- Shichu Custom settings -------- 
# cd() { builtin cd "$@" && ls; }
# The above line can be optimized by
chpwd() {
	ls
}

export KL="szhu28@keeling.earth.illinois.edu"
export DT=" -p 49222 shichu@lostandfoundii.ddns.net"
export EWS=" szhu28@linux.ews.illinois.edu"
alias pfwdto="ssh -N -f -L 8103:localhost:8103 "
alias klpy="ssh $KL 'screen -dm bash -c ipynbhpc'"
alias dtpy="ssh $DT 'screen -dm bash -c \"/home/shichu/usr/anaconda3/bin/jupyter notebook --no-browser --port 8103\"'"
alias upfwd='kill $(ps aux | grep "ssh" | awk '"'"'{print $2}'"'"') '
#ssh $DT 'echo $(ps aux |grep "[j]upyter-notebook" |awk '"'"'{print $2}'"'"')'
#The following line generated by s/'/'"'"'/g from the line above
alias udt='ssh $DT '"'"'kill $(ps aux |grep "[j]upyter-notebook" |awk '"'"'"'"'"'"'"'"'{print $2}'"'"'"'"'"'"'"'"')'"'"

# For Haskell stack
export PATH="/home/shichu/.local/bin:$PATH"

# For golang & drive odeke
export GOPATH=$HOME/usr/gopath
export PATH=$GOPATH:$GOPATH/bin:$PATH

# For distinguish zsh/bash in workingWithWorkspace.sh
export FLAG_ZSH=True
. $HOME/workspace/bin/workingWithWorkspace.sh

# added by Anaconda3 installer
export PATH="/home/shichu/usr/anaconda3/bin:$PATH"
# For jupyter notebook to utilize GPU process.
export BROWSER=google-chrome

# For Apache hadoop / spark
export PATH="/home/shichu/usr/apache/hadoop-3.0.0/bin:/home/shichu/usr/apache/spark-2.3.0-bin-hadoop2.7/bin:$PATH"
