version: "3.3"
services:
    nvidia:
        ulimits:
            memlock: -1
            stack: 67108864
        volumes:
            - '/mnt/shichu/tmp:/workspace/tmp'
        ports:
            - '8888:8888'
        image: 'nvcr.io/nvidia/tensorflow:20.12-tf2-py3'
        stdin_open: true
        tty: true
        shm_size: 1073741824
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        runtime: nvidia
        command: "python tmp/main.py"
